### ISSUE TITLE
Provide guidance for using the device authorization grant

### ISSUE THREAD

**Issue by wazzamatazz** [intelligentplant/py-app-store-api#45]
The November 2024 release of the Industrial App Store adds support for signing users into apps using the [OAuth 2.0 device authorization grant](https://datatracker.ietf.org/doc/html/rfc8628).

Given that the Python tools do not enforce the use of a particular OAuth library, it would be useful to provide guidance and examples in this repository on how to use this grant type from within a Python script, or to implement the device authorization grant without the use of an external library.

Guidance is also required about how to manage authentication tokens (access tokens and refresh tokens), in particular in scenarios where refresh tokens are being issued. In our .NET tools, we automatically encrypt tokens for command-line apps using the ASP.NET Core data protection libraries; guidance and/or libraries for protecting tokens in Python should also be provided.

**Comment by RossRKK** [comment]
I have added a session manager which uses the library keyring to store these tokens in the host OS's  key vault.
https://pypi.org/project/keyring/
